# -*- coding: utf-8 -*-
{
    'name': 'odoo_padel_reservation_management',
    'version': '19.0.1.5.4',
    'category': 'Website/Appointment',
    'summary': 'Gestion de reservas de pistas de padel para Odoo.sh 19 con disponibilidad web e interna.',
    'author': 'Camping Fuente',
    'website': 'https://www.campingfuente.com',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'calendar',
        'website',
        'portal',
        'sale',
        'website_sale',
        'payment',
        'account',
        'point_of_sale',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/product_data.xml',
        'data/ir_cron.xml',
        'views/padel_court_views.xml',
        'views/padel_price_rule_views.xml',
        'views/padel_court_block_views.xml',
        'views/padel_booking_views.xml',
        'views/padel_recurring_booking_wizard_views.xml',
        'views/padel_manual_payment_wizard_views.xml',
        'views/padel_redsys_refund_confirmation_wizard_views.xml',
        'views/res_config_settings_views.xml',
        'views/menu_views.xml',
        'views/website_templates.xml',
        'views/portal_templates.xml',
        'views/internal_planning_templates.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'odoo_padel_reservation_management/static/src/js/padel_booking.js',
            'odoo_padel_reservation_management/static/src/scss/padel_booking.scss',
        ],
        'web.assets_backend': [
            'odoo_padel_reservation_management/static/src/js/padel_draft_leave_guard.js',
        ],
    },
    'application': True,
    'installable': True,
}
